services:
  dbmysql:
    container_name: alten-dbmysql
    image: 'mysql/mysql-server:8.0'
    volumes:
      - /data/mysql
    environment:
      MYSQL_DATABASE: alten
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    expose:
      - "3301"
    ports:
      - '3301:3306'
    networks:
      - alten-app
    restart: always
  alten-app:
    image: alten-app
    build:
      context: ../alten
    ports:
      - '8087:8080'
    volumes:
      - /data/alten-app
    depends_on:
      - dbmysql
    networks:
      - alten-app
networks:
  alten-app:
      name: alten-app